<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>Main</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Webview</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.jelosperone.Webview</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">29.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<AssemblyTitle>xvideo</AssemblyTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <NoWarn>1701;1702;1416</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-maccatalyst|AnyCPU'">
	  <NoWarn>1701;1702;1416</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'">
	  <NoWarn>1701;1702;1416</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <NoWarn>1701;1702;1416</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-maccatalyst|AnyCPU'">
	  <NoWarn>1701;1702;1416</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.19041.0|AnyCPU'">
	  <NoWarn>1701;1702;1416</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<AndroidResource Include="Platforms\Android\mipmap\appicon.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <Color>#512BD4</Color>
		</AndroidResource>
		<MauiIcon Include="Resources\AppIcon\appicon.png" Color="#512BD4">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</MauiIcon>

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.png" Color="#FFFFFF" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="8.0.0" />
		<PackageReference Include="FFImageLoading.Maui" Version="1.3.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.100" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="SharpZipLib" Version="1.4.2" />
		<PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Business\Business.csproj" />
	  <ProjectReference Include="..\Common\Common.csproj" />
	  <ProjectReference Include="..\Repository\Repository.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <MauiFont Update="C:\Users\jean-\.nuget\packages\syncfusion.maui.core\33.1.44\buildTransitive\..\buildTransitive\Resources\Fonts\MauiMaterialAssets.ttf" Link="Resources\Fonts\MauiMaterialAssets.ttf" />
	  <MauiFont Update="C:\Users\jean-\.nuget\packages\syncfusion.maui.toolkit\1.0.9\buildTransitive\..\buildTransitive\Resources\Fonts\MauiMaterialAssets.ttf" Link="Resources\Fonts\MauiMaterialAssets.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Drawables\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Templates\ProductTemplate.xaml.cs">
	    <DependentUpon>ProductTemplate.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Templates\WorkTemplate.xaml.cs">
	    <DependentUpon>WorkTemplate.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Pages\EditNotePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\EditSettingPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Templates\ProductTemplate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Templates\WorkTemplate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Templates\NoteTemplate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
